### ISSUE TITLE
No such element while generating file details.

### ISSUE THREAD

**Issue by sachintyagi22** [Imaginea/KodeBeagle#600]
java.util.NoSuchElementException: key not found: hqapi1-integration-tests/src/test/java/org/hyperic/hq/hqapi1/test/AgentTransferPlugin_test.java
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:58)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:64)
	at com.kodebeagle.model.JavaFileInfo.fileDetails(JavaRepo.scala:126)
	at com.kodebeagle.spark.RepoAnalyzerJob$.handleJavaRepoFiles(RepoAnalyzerJob.scala:189)
	at com.kodebeagle.spark.RepoAnalyzerJob$.com$kodebeagle$spark$RepoAnalyzerJob$$handleJavaRepos(RepoAnalyzerJob.scala:145)
	at com.kodebeagle.spark.RepoAnalyzerJob$$anonfun$handleJavaIndices$1$$anonfun$apply$4.apply(RepoAnalyzerJob.scala:122)
	at com.kodebeagle.spark.RepoAnalyzerJob$$anonfun$handleJavaIndices$1$$anonfun$apply$4.apply(RepoAnalyzerJob.scala:122)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.kodebeagle.spark.RepoAnalyzerJob$$anonfun$handleJavaIndices$1.apply(RepoAnalyzerJob.scala:122)
	at com.kodebeagle.spark.RepoAnalyzerJob$$anonfun$handleJavaIndices$1.apply(RepoAnalyzerJob.scala:120)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$33.apply(RDD.scala:920)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sachintyagi22** [comment]
Details: 

This looks some special case where file shows up in git tree but the git log does not mention it. Also, if we look the at the file on github it shows zero contributors. Not sure when will this happen.

Fix: Given that there's no useful information to collect anyway from this file's history (author, co-change etc), we can safely ignore such cases without giving up on much.

TODO: But we still need to be able to explain this behavior. So revisit this later.
